### ISSUE TITLE
default_schema rename to default_tenant undocumented in ChangeLog

### ISSUE THREAD

**Issue by betelgeuse** [rails-on-services/apartment#101]
## Steps to reproduce

Upgrade ros-apartment 2.7.2 (was 2.6.1)

## Expected behavior

CHANGELOG.m documents breaking changes

You also should not rename historical entries for the old term:

https://github.com/rails-on-services/apartment/commit/9c42715b0892297cb4066af8d357b2ccebaacace#r41169703

## Actual behavior

```
NoMethodError: undefined method `default_schema=' for Apartment:Module
Did you mean?  default_tenant=
```

**Comment by rpbaltazar** [comment]
Thank you for the feedback. you're totally right. I'll fix the historical entries, fix the minor version and release a major version
