### ISSUE TITLE
Could not find generator 'apartment:install'.

### ISSUE THREAD

**Issue by opedrosouza** [rails-on-services/apartment#105]
## Steps to reproduce
Just create a new Rails 6.0.3 application with postgres database and add the `ros-apartment, require: 'apartment'` and run bundle install

## Expected behavior
That give me the rails g apartment:install task

## Actual behavior
Don't have the rails g apartment:install task but has the others like apartment:create /migrate, etc

## System configuration
Ruby 2.7.1
Rails 6.0.3
Postgres

**Comment by codedals** [comment]
Having the same issue.

**Comment by rpbaltazar** [comment]
That is odd. 
I tried on my machine and it seems to work... is there any error that it outputs?

(apologies for the typos along the way...)

https://user-images.githubusercontent.com/5548466/105369634-b71fb100-5c3d-11eb-9df4-04ac2f2a799d.mov

There is a logged error in the terminal but that is spring acting up. the configuration gets created

**Comment by blacksyan** [comment]
Have same issue, 
```
bundle exec rails generate apartment:install
Running via Spring preloader in process 23312
Could not find generator 'apartment:install'. Maybe you meant 'rspec:install', 'pundit:install' or 'paper_trail:install'
Run `rails generate --help` for more options.
```

After move `gem 'ros-apartment', require: 'apartment'` up under pg gem, it works.
```
bundle exec rails generate apartment:install
Running via Spring preloader in process 23655
      create  config/initializers/apartment.rb
```

**Comment by rpbaltazar** [comment]
Is it because spring is running and it's not reloading the configuration? and by changing the order of the gems somehow you're forcing spring to reload which then makes it find the apartment? Can you try to delete the file, move the gem back up in the list of the gemfile and run it again, please?
