### ISSUE TITLE
Detach from original repo?

### ISSUE THREAD

**Issue by louim** [rails-on-services/apartment#106]
Hey!

The gem is great, it would be nice to detach the gem from the upstream `influitive/apartment` repo, so the search works on this repo. This can be done by contacting Github support. What do you think?

**Comment by rpbaltazar** [comment]
I've thought about that. Also when PRs get opened, they are always defaulting to the original repo.
I think it might be time for that.

**Comment by rpbaltazar** [comment]
Done.
