### ISSUE TITLE
I'd like to add a Wiki...

### ISSUE THREAD

**Issue by ben-gy** [rails-on-services/apartment#107]
Apologies, I couldn't see a contact email so I've posted an issue.

Is it possible that you could turn on the Wiki functionality for this gem?

I've spent a lot of time consolidating information creating a pattern that uses a series of callbacks on a Tenant model that synchronises subdomain/domain CRUD actions in the database with a Heroku instance via Heroku's Platform API.

I think this could be useful for a lot of people using this gem. For now, here's a snapshot of what I've done...
```
class Organisation < ApplicationRecord

  # version control
  has_paper_trail

  # validations
  validates :name, length: { in: 3..100 }, presence: true
  validates :subdomain, length: { in: 3..20 }, presence: true, uniqueness: true

  validates { subdomain_available_on_heroku } unless Rails.env.development?

  after_create { create_tenant }
  after_destroy { remove_tenant }
  after_save  { rename_tenant }

  private

    def subdomain_available_on_heroku
      # get list of domains from Heroku
      domain_list = heroku.domain.list(app_id)

      # check if domains include the subdomain and abort if so
      if domain_list.include?(self.subdomain)
        errors.add(:subdomain, 'something has gone wrong - the subdomain is available in the database but not available on Heroku')
        throw(:abort)
      end
    end

    def create_tenant
      Apartment::Tenant.create(self.subdomain)

      # create the subdomain on heroku
      unless Rails.env.development?
        heroku.domain.create(ENV['HEROKU_APP_ID'], "#{self.subdomain}.#{ENV['DOMAIN_NAME']}")
      end
    end

    def remove_tenant
      Apartment::Tenant.drop(self.subdomain)

      # cleanup the subdomain on heroku
      unless Rails.env.development?
        heroku.domain.delete(ENV['HEROKU_APP_ID'], "#{self.subdomain}.#{ENV['DOMAIN_NAME']}")
      end
    end

    def rename_tenant
      if self.paper_trail.previous_version.present? && self.paper_trail.previous_version.subdomain != self.subdomain
        ActiveRecord::Base.connection.execute("ALTER SCHEMA \"#{self.paper_trail.previous_version.subdomain}\" RENAME TO \"#{self.subdomain}\";")

        # cleanup the subdomain on heroku
        unless Rails.env.development?
          heroku.domain.delete(ENV['HEROKU_APP_ID'], "#{self.paper_trail.previous_version.subdomain}.#{ENV['DOMAIN_NAME']}")
          heroku.domain.create(ENV['HEROKU_APP_ID'], "#{self.subdomain}.#{ENV['DOMAIN_NAME']}")
        end
      end
    end
end
```

**Comment by rubendinho** [comment]
Very cool. I have also played with the Heroku API quite a bit and this would be nice to document.

Are you also provisioning databases via the Heroku API or using schemas?

Given the confusing state of disparate documentation across multiple instances of this project, a wiki would be a most welcome resource.

--
*
*
*Ruben Izmailyan*

Founder & CEO, Quiltt ( http://www.quiltt.io )
469-608-0470
ruben@quiltt.io
linkedin ( https://www.linkedin.com/in/rubenizmailyan/ ) | twitter ( https://twitter.com/rubendinho )

**Comment by ben-gy** [comment]
Thanks 😊 

I’m using schemas currently. So I can’t actually access the wiki on this gem? I can see the tab but I’m redirected back to the readme when clicking on it. I don’t have this issue with other repositories. Can you please add me as a collaborator and/or open up the wiki to allow public access and contribution?

Cheers 🍻

**Comment by rubendinho** [comment]
Sorry I’m not a maintainer but I definitely think a wiki would be a great
addition to this project.

--

*Ruben Izmailyan*
Founder & CEO, Quiltt <http://www.quiltt.io/>
469-608-0470
ruben@quiltt.io
linkedin <https://www.linkedin.com/in/rubenizmailyan/> | twitter
<https://twitter.com/rubendinho>

**Comment by rpbaltazar** [comment]
Agree. Happy if you can help out with that. I have not had much time to focus on this gem in the last few weeks.

**Comment by rpbaltazar** [comment]
@ben-gy I had added you as contributor to the project a while ago. Since you hadn't had the chance to update the wiki (or maybe something wrong and you still can't access it), I went ahead and copied your ticket info to the wiki page. 
If you're still interested in updating the wiki, please let me know if you can access it, else i'll look into what might be wrong with it.
Feel free to reach me via email as well.
