### ISSUE TITLE
not exclued model / tbl 

### ISSUE THREAD

**Issue by victhor9696** [rails-on-services/apartment#108]
I have a problem and I can't find anything in a place or on an

even adding models to exclude the new schemas are being created with the tables

config.excluded_models = ["Recruiter", "Account", "Access", "Admin", "Business", "Identity", "Lead", "Plan", "Transaction", "Subscription"]
  config.tenant_names = -> {Account.pluck: tenant}

I have no idea why tables are being created, do you have any tips on where to look for an answer, or how to debug?

**Comment by CR1AT0RS** [comment]
Sam issue here. I have the same issue as my table are not getting excluded:
  config.excluded_models = %w{ AdminUser Organization Account }
  config.excluded_models = ["User", "AdminUser", "Account", "Organization"]

No matter what I add in config.excluded_models nothing happens and all models are included.

**Comment by timrwilliams** [comment]
Are you seeing data in those tables in your new schemas or just the tables being created?

As per the documentation the tables are always created in all schemas but should be empty: https://github.com/rails-on-services/apartment#excluding-models

**Comment by CR1AT0RS** [comment]
In new "schemas" that are being created. I've moved to ac_as_tenant @victhor9696 !

**Comment by rpbaltazar** [comment]
As pointed by @timrwilliams the tables are created in all tenants and all tenants should have the same tables. The key difference is the way these exclusion is made is that it does not include the tenant name in the search path when querying those excluded models.

**Comment by rpbaltazar** [comment]
@CR1AT0RS understand you decided to move to `act_as_tenant`. I'm just trying to confirm that i understood your issue correctly. Models that were excluded, were being recorded in the schema of the current tenant, is it? or you were seeing the tables in all schemas, but they were all empty and records were created in the default schema?
