### ISSUE TITLE
Check if tenant exists?

### ISSUE THREAD

**Issue by CR1AT0RS** [rails-on-services/apartment#110]
## Steps to reproduce
How can I do something like:
Apartment::Tenant.exists('tenant_name')?

I wanna check if a tenant exists before creating it.

## System configuration

* Database: (Tell us what database and its version you use.)

* Apartment version:

* Apartment config (in `config/initializers/apartment.rb` or so):

  * `use_schemas`: (`true` or `false`)

* Rails (or ActiveRecord) version:

* Ruby version:

**Comment by pedromschmitt** [comment]
You can do this:
`apartments = Apartment.tenant_names.sort`
`apartments.include?('tenant-you-want-to-check')`


I get this from a pry script on Stackoverflow that helps a lot when working on rails console: https://stackoverflow.com/a/53251641/3650719

**Comment by CR1AT0RS** [comment]
@pedromschmitt 

I am not sure what's going on but everything works except the [43] 
pry(main)> Apartment.tenant_names.sort
     (1.5ms) SELECT "database" FROM "users"  []
=> []
T.names 
Always return nil. 

T.me returns the "public" schema which is correct. What SQL query should it execute on T.exists?

**Comment by pedromschmitt** [comment]
@CR1AT0RS  

The SQL that runs here when writing `Apartment.tenant_names.sort` at rails console is:
`   (0.5ms)  SELECT "public"."accounts"."subdomain" FROM "public"."accounts"`


What is your name's configuration at `config/initializers/apartment.rb`?
Example:
`  config.tenant_names = lambda { Account.pluck :subdomain }
`

**Comment by rpbaltazar** [comment]
@CR1AT0RS does the ❤️ mean it has solved your challenge and we can close the issue?

**Comment by CR1AT0RS** [comment]
Yes sir!
