### ISSUE TITLE
[ActiveJob::DeserializationError] solution: require "apartment"

### ISSUE THREAD

**Issue by nbw** [rails-on-services/apartment#114]
I'm relaying this message on behalf of a colleague who upgraded us to Rails 6.

We run a rails app with Apartment and upgraded to Rails 6. 
We use sidekiq.

We were running into a `ActiveJob::DeserializationError` due to name conflicts.

To get around it:

Gemfile:
```ruby
gem 'ros-apartment', require: 'apartment'
gem 'ros-apartment-sidekiq', require: 'apartment/sidekiq'
```

Apparently this error came up on the sidekiq side. 

It would be nice if the Readme was updated for others moving forward.

Thanks for your work!

**Comment by rpbaltazar** [comment]
@nbw Thanks for the heads up. I suppose you're referring to this: https://github.com/rails-on-services/apartment-sidekiq/pull/1 right?
