### ISSUE TITLE
db/schema.rb not update on migration

### ISSUE THREAD

**Issue by GaboFDC** [rails-on-services/apartment#117]
## Steps to reproduce

If you don't use the public schema a a tentant, which for our sould be a best practice. Then after running migrations, rails will dump the schema, and is left practically empty. We believe that rails is using the default public schema for the dump, and that is the reason. But were unable to correctly pinpoint how to fix it. If anyone can prove gidance we are willing to contribute a PR for this.

## Expected behavior
When not using public schema, aparment should use other tenant for generating the schema. Anyways all tenants should have the same schema so using any other should give no problem.

## Actual behavior
db/schema.rb is leaved almost empty.

## System configuration

* Database: postgres

* Apartment version: 2.7.2

* Apartment config (in `config/initializers/apartment.rb` or so):
```
require 'apartment/elevators/generic'

Apartment.configure do |config|
  config.tenant_names = ['alpha_generales']
  config.persistent_schemas = ['public']
end

Rails.application.config.middleware.use Apartment::Elevators::Custom

```

  * `use_schemas`: (`true` or `false`)

* Rails (or ActiveRecord) version: 6.0.3.4

* Ruby version: ruby-2.7.0

**Comment by rpbaltazar** [comment]
Interesting request. I'll have to dig into the source to understand how is the schema dump tied to the public schema. I'll try to put in some hours into this. If anyone wants/has the time to do it, help is appreciated.

**Comment by GaboFDC** [comment]
We tried to dig it out, but it was a bit complex, we switched to not use the public schema as persistent, ans use another tenant instead.
