### ISSUE TITLE
Rails 6.1 compatibility

### ISSUE THREAD

**Issue by walski** [rails-on-services/apartment#121]
## Steps to reproduce

* Use `gem 'rails', '~> 6.1.rc1'` and `gem 'ros-apartment', require: 'apartment'` in the same application

## Expected behavior

It lets you install the bundle.

## Actual behavior

It fails due to the [current strict requirement of a Rails version < 6.1](https://github.com/rails-on-services/apartment/blob/db454b562cf1d993831415394b233c21a04efd8c/ros-apartment.gemspec#L30)

## Proposed Change

Specs run fine when relaxing the Rails version requirement to `< 6.2` in the gemspec. Would love to open a PR with this change if that is ok with current release standards. Cheers!

**Comment by walski** [comment]
This is really all there is to it: https://github.com/walski/apartment/commit/1353b8de986921b6720ad7beab28adf54849691b

**Comment by rpbaltazar** [comment]
https://github.com/rails-on-services/apartment/pull/122
