### ISSUE TITLE
New version raises an error with ActiveSupport::LogSubscriber 

### ISSUE THREAD

**Issue by nicolasrsande** [rails-on-services/apartment#128]
Hello, i just updated to the new version on rails 6.0.3 and i get a NameError for ActiveSupport::LogSubscriber. 

I think it has to be with the recent changes to support version 6.1 like this one #125. Is the gem no longer offer compatibility with 6.0.3 apps? I plan to update but not yet because 6.1 is too recent and some gems get broken.

**Comment by rpbaltazar** [comment]
It was not meant to break anything. Will look into it and fix it

**Comment by nickgal** [comment]
I ran into this as well on 6.1.

As a temporary fix I added `require 'active_record/log_subscriber'` to my application.rb before the Bundler.require call.

**Comment by rpbaltazar** [comment]
@nicolasrsande can you test the development branch? I've currently an issue with the CI #130 which i'm trying to work out so until then I can't feasibly run the test suite.

**Comment by nicolasrsande** [comment]
@rpbaltazar Sure, I will test it tomorrow morning and let you know the result.

**Comment by nicolasrsande** [comment]
@rpbaltazar Confirmed development branch changes fix the error. All test passed. For me it's ready to merge.
