### ISSUE TITLE
Add console info about tenants and fast switches

### ISSUE THREAD

**Issue by rpbaltazar** [rails-on-services/apartment#14]
This is an enhancement proposal based on our use case. It is open for discussion and if we don't think its valuable for the users (or it bloats the project with unnecessary things) it can be released separately.

When we run the console in a project with apartment, generally we need to switch across tenants or execute some tasks within a specific tenant. We found it useful to have that info printed in the prompt. E.g

```bash
$ be rails c
$pry[public]> User.count
0
$pry[public]> st tenant_one
$[tenant_one]> User.count
10
$[tenant_one]> st
public
tenant_one
tenant_two
$[tenant_one]> st public
$pry[public]>
```

These are console commands that we have as part of our codebase, but could probably be adjusted to work out of the box.

**Comment by joshukraine** [comment]
This sounds very useful!

**Comment by rjayroach** [comment]
Since this is pry specific maybe it should be in a gem `pry-apartment` our code should probably also be refactored to allow hooks like `after_switch` so things like setting the tenant credential would be pluggable.
