### ISSUE TITLE
DB connection not skipped for bin/rails assets:precompile for Rails 6.1

### ISSUE THREAD

**Issue by oleksii-leonov** [rails-on-services/apartment#142]
Now apartment use ARGV-based check to skip DB connection for `assets:precompile`, `assets:clean` and `webpacker:compile` tasks: https://github.com/rails-on-services/apartment/blob/d97d55bd45dc733671c8020c69a0122d3a044173/lib/apartment/railtie.rb#L34

It works in Rails 6.0. But starting Rails 6.1 ARGV cleared in `Rails::Command.invoke`: https://github.com/rails/rails/pull/38495.

So, running `bin/rails assets:precompile` would have empty ARGV. So, a DB connection would be established (however expected to be skipped).

I believe it's not an important issue, but it may be confusing during an update to Rails 6.1.

As possible workarounds:
- run `bin/rake assets:precompile` instead of `bin/rails assets:precompile`;
- `APARTMENT_DISABLE_INIT` env to skip DB init manually.

**Comment by stevschmid** [comment]
The workaround with `APARTMENT_DISABLE_INIT` does not work me straight away. These `require`s somehow still load a connection https://github.com/rails-on-services/apartment/blob/6ce41138337a46829e9a06ff31c7811a7e42aa18/lib/apartment.rb#L11-L18

Commenting them out and using `APARTMENT_DISABLE_INIT` works.
