### ISSUE TITLE
Apartment::TenantNotFound raised randomly in production

### ISSUE THREAD

**Issue by giovapanasiti** [rails-on-services/apartment#166]
## Steps to reproduce

I just deployed my tenant app on digitalocean app platform and digitalocean postgres db

## Expected behavior

when the use hit the right subdomain it should switch to the right tenant. It usually works but sometimes sentry caught this error.

## Actual behavior

randomly it raises `Apartment::TenantNotFound`
`One of the following schema(s) is invalid: "mainapp" "public", "shared_extensions"`

## System configuration

* Database: (Tell us what database and its version you use.)
Postgres 12

* Apartment version:
`ros-apartment (2.9.0)`

* Apartment config (in `config/initializers/apartment.rb` or so):

```ruby
config.persistent_schemas = ["shared_extensions"]
  config.tenant_names = -> { Account.pluck :subdomain_name }
  config.excluded_models = ["Account", 'ActionMailbox::InboundEmail']
  config.active_record_log = true
  Apartment::Elevators::Subdomain.excluded_subdomains = ["www", "admin", "public", "saladilprealpha"]
  Apartment::Elevators::FirstSubdomain.excluded_subdomains = ["www", "admin", "public", "saladilprealpha"]

....

Rails.application.config.middleware.use Apartment::Elevators::Subdomain

```

* `use_schemas`: `true` 

* Rails (or ActiveRecord) version:
`rails (~> 6.1.3.1)`

* Ruby version:
`ruby 3.0.0p0`

**Comment by rpbaltazar** [comment]
@giovapanasiti with the latest version, the work of @lunks has been made available. it does not fix the problem per se but it should allow you to understand what the underlying cause of the problem is. 
We should probably aim at better erroring in general
