### ISSUE TITLE
Switch callbacks on create tenant

### ISSUE THREAD

**Issue by jonian** [rails-on-services/apartment#179]
Hi @rpbaltazar, I use switch callbacks in my application to change the tenant locales. The locale preferences for the tenant are pulled from a settings table.

The issue I'm having is that on tenant creation the switch callbacks are fired before the schema tables are created. Any ideas on how to handle this?

My switch callback config:

```ruby
Apartment::Adapters::AbstractAdapter.set_callback :switch, :after do
  if current == default_tenant
    # reset locales to application default
  else
    # set locale from settings table
  end
end
```

**Comment by rpbaltazar** [comment]
Hi @jonian 

let me try to replicate the issue on my dev env and see what i can do about it. If you have worked out a solution, please share it
