### ISSUE TITLE
Rails 7 Wrong schema_search_path in ActiveStorage::DirectUploadsController

### ISSUE THREAD

**Issue by fdaugs** [rails-on-services/apartment#196]
## Steps to reproduce
After upgrading our app to Rails 7.0.2 from 6.1.4, the direct upload no longer works together with the apartment. Blob records are always created in the default schema (or whatever is configured as schema_search_path in database.yml). And if you try to attach such a record to a model, an error is issued because the record cannot be found in the current tenant's schema.

## Expected behavior
Blobs should be created the schema of the current tenant.

## Actual behavior
The schema_search_path in the create method of the ActiveStorage::DirectUploadsController is set to the default and blobs are inserted in the default schema.

* Database: postgres 11

* Apartment version: 2.11.0 (I also tried the fix in #194)

* Apartment config (in `config/initializers/apartment.rb` or so):

  * `use_schemas`: `true` 
  * `use_sql`:  `true` 

* Rails (or ActiveRecord) version: 7.0.2

* Ruby version: 2.7.5

**Comment by archonic** [comment]
I'm also seeing 404s on files and even more worrisome is that existing URLs are linking to attachments in other workspaces.

**Comment by acallaghan** [comment]
I'm also seeing this problem with Rails 7.

For my application, `ActiveStorage::Blob` is in each schema, but after upgrading to Rails 7, Rails always chooses the public schema for calls to `ActiveStorage::Blob Load`

E.g. ```
[public,shared_extensions]   ActiveStorage::Blob Load (0.8ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1 LIMIT $2  [["id", 28], ["LIMIT", 1]]

ActiveRecord::RecordNotFound (Couldn't find ActiveStorage::Blob with 'id'=28):
```

I'll try and muck around on a branch and find a fix

**Comment by acallaghan** [comment]
I've opened a PR that might be the fix: https://github.com/rails-on-services/apartment/pull/198

**Comment by ThomAille** [comment]
Hi all, 

It's not optimized and not very pretty as code, but here is the solution we developed to solve the problem

`app/controllers/active_storage/direct_uploads_controller.rb`

```ruby 
# frozen_string_literal: true

# Creates a new blob on the server side in anticipation of a direct-to-service upload from the client side.
# When the client-side upload is completed, the signed_blob_id can be submitted as part of the form to reference
# the blob that was created up front.
class ActiveStorage::DirectUploadsController < ActiveStorage::BaseController
  def create
    subdomain = Apartment::Tenant.current
    blob = nil
    Apartment::Tenant.switch(subdomain) do
      blob = ActiveStorage::Blob.create_before_direct_upload!(**blob_args)
    end
    render json: direct_upload_json(blob)
  end

  private
  def blob_args
    params.require(:blob).permit(:filename, :byte_size, :checksum, :content_type, metadata: {}).to_h.symbolize_keys
  end

  def direct_upload_json(blob)
    blob.as_json(root: false, methods: :signed_id).merge(direct_upload: {
      url: blob.service_url_for_direct_upload,
      headers: blob.service_headers_for_direct_upload
    })
  end
end

```

**Comment by archonic** [comment]
I'm uncertain why this would fix anything:
```
subdomain = Apartment::Tenant.current
Apartment::Tenant.switch(subdomain)
```
Wouldn't Apartment already be switched to the current tenant?

**Comment by ArthurWD** [comment]
> I'm uncertain why this would fix anything:

It seems like somewhere deep in active storage the schema is reset, without Apartment knowing about this.

We came up with this fix in an initializer:

```
module ActiveStorageApartmentFix
  extend ActiveSupport::Concern

  def key
    self[:key] ||= "#{Apartment::Tenant.current}/#{self.class.generate_unique_secure_token(length: 28)}"
  end

  class_methods do
    def create_before_direct_upload!(**args)
      Apartment::Tenant.switch(Apartment::Tenant.current) do
        super
      end
    end
  end
end

Rails.application.config.to_prepare do
  ActiveStorage::Blob.prepend(ActiveStorageApartmentFix)

  ActiveRecord::Base.class_eval do
    def self.find_signed!(signed_id, purpose: nil)
      Apartment::Tenant.switch(Apartment::Tenant.current) do
        super
      end
    end
  end
end
```

**Comment by dirkbull** [comment]
Thanks @ArthurWD for the quick fix. Small addition for those who need to avoid initializing Apartment while precompiling assets:

```ruby
module ActiveStorageApartmentFix
  extend ActiveSupport::Concern

  def key
    self[:key] ||= "#{Apartment::Tenant.current}/#{self.class.generate_unique_secure_token(length: 28)}"
  end

  class_methods do
    def create_before_direct_upload!(**args)
      Apartment::Tenant.switch(Apartment::Tenant.current) do
        super
      end
    end
  end
end

Rails.application.config.to_prepare do
  next if ENV['APARTMENT_DISABLE_INIT']

  ActiveStorage::Blob.prepend(ActiveStorageApartmentFix)

  ActiveRecord::Base.class_eval do
    def self.find_signed!(signed_id, purpose: nil)
      Apartment::Tenant.switch(Apartment::Tenant.current) do
        super
      end
    end
  end
end
```
