### ISSUE TITLE
upcoming Rails 6 multi-database

### ISSUE THREAD

**Issue by rpbaltazar** [rails-on-services/apartment#2]
Linking a few issues still open in the original apartment that I think might be worth to look at in the immediate:

- https://github.com/influitive/apartment/issues/617
- https://github.com/influitive/apartment/issues/602
- https://github.com/influitive/apartment/issues/571
- https://github.com/influitive/apartment/issues/565
- https://github.com/influitive/apartment/issues/563
- https://github.com/influitive/apartment/issues/559

**Comment by rpbaltazar** [comment]
https://github.com/influitive/apartment/issues/629

**Comment by jean-francois-labbe** [comment]
@rpbaltazar hello, I use apartment in production with rails 6.0.2.1 and could help you with some pull requests if needed.
I tried your version but I'm getting the error described here: #3 

Let me know if you need help

**Comment by rpbaltazar** [comment]
Hi @jean-francois-labbe sounds good. I'm planning to go over a few things over the weekend and see what i can start doing with the read/write databases for rails 6. I'll update this issue with the findings.
I'm more than happy to have some more people involved in this

**Comment by rpbaltazar** [comment]
@jean-francois-labbe I've created a rails-6-demo from a boilerplate repo I found.
I've added the latest ros-apartment gem and tried the read/write replica feature in rails 6. I have not found any issues in this sample app. 
It looks like its working and I have not encountered any issues.

**Comment by rpbaltazar** [comment]
Closing this issue for now as we're running rails 6 without any known issues.

**Comment by marksiemers** [comment]
@rpbaltazar - We are looking to switch to this fork of apartment and upgrade to rails 6.

Since this gem requires the original aparment, the gemspec there is still locking rails `< 6.0` Is there a recommended way to unlock that?

**Comment by rpbaltazar** [comment]
This actually does not require the original gem. `require: 'apartment'` is needed because the gem name does not match the main module but it is entirely independent. In fact there is a ticket proposing to detach from the original fork
