### ISSUE TITLE
Add config.included_models

### ISSUE THREAD

**Issue by ramaboo** [rails-on-services/apartment#204]
We run a large app where 90% of our app is not using Apartment. We really only use it for two tables. This makes config.excluded_models not work so well for us as ever new model we add we have to go and manually exclude it. It would be much simpler if we could do `config.included_models` instead. Right now we run code like this:

```
      included_models = %w[Widget Classification]
      manual_exclude = %w[UserRole]
      active_storage = %w[ActiveStorage::Attachment ActiveStorage::Blob ActiveStorage::VariantRecord]
      all_models = ApplicationRecord.connection.tables.map do
        model_name = _1.capitalize.singularize.camelize

        Module.const_defined?(model_name) ? model_name : nil
      end.compact.sort

      config.excluded_models = all_models - included_models + manual_exclude + active_storage
      
   ```
   
   But it's not ideal and error prone. I was wondering if there are any plans to support config.included_models or if someone familiar with the code base could point me in a direction for starting that work?

**Comment by kapso** [comment]
We use this popular gem Rolify (https://github.com/RolifyCommunity/rolify) - which uses an internal table (for some internal join queries), that is not manifested as an ActiveRecord model, and thus there's no way to manifest it as an `excluded_models`.

An `included_models` option will make this gem more compatible with other gems.
