### ISSUE TITLE
Use ActiveSupport::CurrentAttributes in apartment-sidekiq for apartment name

### ISSUE THREAD

**Issue by jordan-brough** [rails-on-services/apartment#205]
Sidekiq recently added support for [ActiveSupport::CurrentAttributes](https://api.rubyonrails.org/classes/ActiveSupport/CurrentAttributes.html):

* [sidekiq/pull/4982](https://github.com/mperham/sidekiq/pull/4982) — Adds support for `Sidekiq::CurrentAttributes.persist(Myapp::Current)`, which persists a CurrentAttributes class into sidekiq jobs automatically
* [sidekiq/issues/5448](https://github.com/mperham/sidekiq/issues/5448) + [sidekiq/issues/5450](https://github.com/mperham/sidekiq/issues/5450) + [sidekiq/commit/f6e552df](https://github.com/mperham/sidekiq/commit/f6e552dfeb63c8c3fc4e97f9fd10b0e2c6179036#diff-3ea6493e3b9dd0a7071089f2ce1d60a8504cc9f1d3790b0fb54807fdcc08fa75) — Displays Current Attributes on the `/queues/xxx` sidekiq admin page

Would y'all be open to a PR that updates apartment-sidekiq to use CurrentAttributes for persisting the tenant on Sidekiq jobs if the Sidekiq version is high enough (>= 6.3.0)?  Or maybe a configuration option to enable that?

**Comment by mnovelo** [comment]
Sounds good! We'd definitely be open to taking a look if you wrote a PR
