### ISSUE TITLE
Support for Rack v3

### ISSUE THREAD

**Issue by jrreed** [rails-on-services/apartment#232]
Hi,

There's currently a Web Cache Poisoning vulnerability in Rack > `v3.0`
- https://security.snyk.io/vuln/SNYK-RUBY-RACK-1061917

Its been out for a while and Rack released a major version bump to address it in `v3.0.0`
- https://github.com/rack/rack/pull/1733

Rails has also added support for Rack > `v3.0` in the upcoming `v7.1.0` release
- https://github.com/rails/rails/pull/46594#issuecomment-1621834052

However, the `ros-apartment` gem is pinned to `rack < 3.0` which prevents us from upgrading to the latest version of `rack`

Best I can tell is that this was introduced here out of precaution:
https://github.com/rails-on-services/apartment/pull/24

Any chance this could be bumped up to `rack < 4.0`?

Let me know if there's something I can help with -- I'd be happy to submit a PR if this is just a matter of updating the gemspec and running tests.

**Comment by mnovelo** [comment]
Sounds reasonable to me. Let's do this once https://github.com/rails-on-services/apartment/pull/243 is merged

**Comment by luke-hill** [comment]
Does this mean the people working on this gem will be looking at rack3 support?

Also is there a reason the changelog is over 4 years out of date? Do you know if there is a plan to maintain the changelog again @mnovelo

**Comment by mnovelo** [comment]
This summer yes. The priority is to get the specs passing again first

**Comment by mnovelo** [comment]
just merged #253 ! Now just checking everything is looking good in prep for releasing a new version!
