### ISSUE TITLE
Is this gem still being actively maintained?

### ISSUE THREAD

**Issue by kapso** [rails-on-services/apartment#234]
Curious, coz most of the latest issues here have not been addressed.

We ourselves are still using an old branch in our code, coz it was never merged - https://github.com/rails-on-services/apartment/tree/fix-monkeypatch-for-rails-before-62

And with the new Rails 7.1 out, I was wondering if there are any plans of keeping this project updated. Would be nice to know either way, so we can make some alternate plans - given how important this gem is to our project.

Thanks a lot.

**Comment by adrienpoly** [comment]
https://github.com/rails-on-services/apartment/issues/222#issuecomment-1637297906

**Comment by x9sim9** [comment]
I really like apartment and its nice to see someone else taking over from the original maintainer to keep the project alive, but perhaps to prevent this becoming a dead project like the original department gem you could mark that this project is looking for maintainers so it can keep going?

I do feel the MySQL implementation for Apartment is far superior to the Postgres one as using a dedicated database for each tenant as MySQL does is a lot better than using Schemas like the Postgres version does, considering schema limitations with Postgres and backups and restoration issues using a monolith database.

If I spot anything myself while using Apartment I would be happy to raise a PR but unfortunately I am not in a position to be an active maintainer. I do hope someone is able to keep the project alive.

**Comment by kirantpatil** [comment]
CitusDB supports Schema-based sharding with Postgresql 16

https://www.citusdata.com/blog/2023/09/22/adding-postgres-16-support-to-citus-12-1/#schema-based-sharding-improvements

**Comment by rpbaltazar** [comment]
After quite some time waiting for people to volunteer, there have been some people reaching out to me asking to take the ownership of the gem.
I've added most of them to the user group.
@riggleg @mnovelo @IanMcNelly will be handling this moving forward! :)
