### ISSUE TITLE
Rails 7.2 support

### ISSUE THREAD

**Issue by kapso** [rails-on-services/apartment#277]
Any plans for supporting Rails 7.2

**Comment by mnovelo** [comment]
I haven't looked at it yet, but I don't see a reason not to. Once it's officially released, we'll start looking at it more closely. If you wanted to spearhead this, I'd be happy to review a PR 😊

**Comment by kapso** [comment]
@mnovelo Rails 7.2 was released last week

**Comment by mnovelo** [comment]
oh it was released on Saturday. Luckily @npezza93's on top of it and has a PR ready https://github.com/rails-on-services/apartment/pull/278
