### ISSUE TITLE
ActiveRecord::StatementInvalid: PG::DuplicateSchema: ERROR:  schema "insales22810" already exists

### ISSUE THREAD

**Issue by stap780** [rails-on-services/apartment#284]
Hello,

i try create tenant and have error (look attachment).
![schema rb — rails_projects 2024-09-12 15-21-05](https://github.com/user-attachments/assets/11d144ed-a8a6-4390-aea1-c3b8b02f48b4)

Loading development environment (Rails 7.1.4)
  User Pluck (1.2ms)  SELECT "public"."users"."subdomain" FROM "public"."users"
Available Tenants: [nil, "teletri", "test2", "ketago", "support_ketago_com"]
Use `st 'tenant'` to switch tenants & `tenant_list` to see list
[1] [development][public] pry(main)> Apartment::Tenant.create('test1234')
   (12.5ms)  BEGIN;
          CREATE SCHEMA "test1234";
          COMMIT;
   (3.4ms)  CREATE SCHEMA "insales22810"
ActiveRecord::StatementInvalid: PG::DuplicateSchema: ERROR:  schema "insales22810" already exists

from /Users/administrator/.rvm/gems/ruby-3.2.0/gems/activerecord-7.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:55:in `exec'
Caused by PG::DuplicateSchema: ERROR:  schema "insales22810" already exists

from /Users/administrator/.rvm/gems/ruby-3.2.0/gems/activerecord-7.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:55:in `exec'
[2] [development][public] pry(main)> exit

* Database: (Tell us what database and its version you use.) Postgresql 9.5

* Apartment version: 3.1.0

* Apartment config (in `config/initializers/apartment.rb` or so):

  * `use_schemas`: (`true` or `false`) default

* Rails (or ActiveRecord) version: 7.1.4

* Ruby version: 3.2.0

**Comment by stap780** [comment]
as i understand the problem is that file schema.rb have records - create_schema "insales22810" and another

- i drop all tenants.
- open console and one after one add new tenant - all ok
- close console and check schema.rb. and have information about added tenants - create_schema 'test' and etc
- open console and try add one more tenant - and have error.

I don't understand - my file schema.rb need to have information about create_schema ? or something wrong with setup?

**Comment by mnovelo** [comment]
@stap780 the `create schema` lines in the schema.rb were added by Rails, not by Apartment. We have used a similar workaround to this to have this not occur https://github.com/rails-on-services/apartment/pull/276 

I'm looking to include this workaround in the next release of the Apartment gem

**Comment by stap780** [comment]
I right understand that better is to wait while you upgrade gem?

**Comment by gertjanjansen** [comment]
@mnovelo thanks for adding this fix. Would be great if you could include this in the next release.
