### ISSUE TITLE
parallel_migration_threads of anything greater than 1 raises ActiveRecord::ConcurrentMigrationError

### ISSUE THREAD

**Issue by jwg2s** [rails-on-services/apartment#298]
## Steps to reproduce
- Set `config.parallel_migration_threads = 4` (really anything greater than 1 will expose the issue)
- Run `bundle exec rake db:migrate`

## Expected behavior
- All schemas should be migrated without error

## Actual behavior
- `ActiveRecord::ConcurrentMigrationError` error is raised, migrations fail.
```
ActiveRecord::ConcurrentMigrationError:

Cannot run migrations because another migration process is currently running.
```

## System configuration

* Database: Postgres v14.12

* Apartment version: Happens regardless of `ros-apartment` version, but confirmed on `3.1.0` and `2.11.0`

* Apartment config (in `config/initializers/apartment.rb` or so):

  * `use_schemas`: `true`
  * `parallel_migration_threads`: `4`

* Rails (or ActiveRecord) version: `6.1.7.9`

* Ruby version: `3.1.4`

**Comment by mnovelo** [comment]
@jwg2s I need to update our README that parallel migrations won't work unless you implement your own schema-aware advisory locks for migrations. I'm seeking advise for how to advise users who want to use parallel migrations https://github.com/rails/rails/pull/43500#issuecomment-2447817077

**Comment by mnovelo** [comment]
@jwg2s try disabling advisory_locks as noted here https://blog.saeloun.com/2019/09/09/rails-6-disable-advisory-locks/

**Comment by jwg2s** [comment]
Thanks - that worked locally so we're unblocked on at least playing around with it. Curious - do you have a functional example of schema-aware advisory locks anywhere?

**Comment by mnovelo** [comment]
Glad that worked for y'all, at least locally @jwg2s . 

I do not have a functional example of schema-aware advisory locks. IMHO, I don't think they're any safer than removing advisory locks completely, so they're not worth implementing. If someone else does, I'd be happy to include it in a wiki or in the README.

I'll mark this issue as closed for now.

**Comment by leshik** [comment]
> IMHO, I don't think they're any safer than removing advisory locks completely

Sure they're safer @mnovelo. If you remove advisory locks completely and run the same migration twice by accident, then you're screwed. Per-schema locks are used to ensure the second migration fails in this case.

**Comment by mnovelo** [comment]
@leshik I don't think I understand your comment. Are you referring to the schema versions table? The schema versions table isn't affected by the advisory locks AFAIK. Could you elaborate?
