### ISSUE TITLE
[Postgresql users] Help testing development branch in your environment

### ISSUE THREAD

**Issue by rpbaltazar** [rails-on-services/apartment#34]
Hi have made some significant changes on the development branch in order to get the queries to be executed in the right tenant even when using read/write replica in rails 6.

Our product codebase has all its tests passing with this new version and I'm currently running it on our staging environment.

If you're using ros-apartment, or intend to, could you possibly test the development branch against your test suite?

This only applies to projects running postgresql with schemas. Although if you're not using schemas and would like to test the development branch as well, that would be reassuring that I have not broken your projects.

Thank you

**Comment by majksner** [comment]
@rpbaltazar I'm running development branch across multiple environments, I'll let you know if I notice anything wrong. Thanks for the fork!

**Comment by gen0cide** [comment]
Hey @rpbaltazar! Question: I am using postgresql with schemas. I am not however using any read/write replica. One app => one postgres instance. LMK if there's enough change in that paradigm. Happy to test.

**Comment by rpbaltazar** [comment]
@gen0cide thank you. Since I'm touching postgres related connections, it would be great if you could test even if its only one to one app/db.

**Comment by rpbaltazar** [comment]
Closing this issue since we are successfully using read/write replicas in our application in production.
