### ISSUE TITLE
How to exclude all models from engine?

### ISSUE THREAD

**Issue by bjensen** [rails-on-services/apartment#4]
I tried adding this to the apartment initializer: 

```
engine_models = myEngine.constants.map {|c| myEngine.const_get(c) }.select do |const|
  const.class == Class && const < ActiveRecord::Base
end

config.excluded_models = %w[User] + engine_models
```

This works perfectly when run in the console, however engine_models is empty when its being executed as part of initialisation. Does anyone have a good idea?

This is in Rails 6.0.2.1

**Comment by jean-francois-labbe** [comment]
Hi @bjensen I think this is because in development classes are lazy loaded so when the initializer is executed models are not loaded yet.

**Comment by bjensen** [comment]
I think you are right..but do you have any suggestions as to how to get it working in development except for actually having to cut and paste every model name and remember to add to this list whenever we add a new model etc?

**Comment by jean-francois-labbe** [comment]
I don't have the solution for this issue, but you should check rails eager_loading: https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#eager-loading

**Comment by rpbaltazar** [comment]
@bjensen You might be able to get around with something close to what you have:

```
engine_models = myEngine.constants.map {|c| myEngine.const_get(c) }.select do |const|
  const.class == Class && const < ActiveRecord::Base
end

engine_models.each do {|em| require em }

config.excluded_models = %w[User] + engine_models
```
Out of curiosity, what is the use case behind this?

**Comment by rjayroach** [comment]
Does `ActiveRecord::Base.connection.tables` get the job done?

**Comment by rpbaltazar** [comment]
Closing this as it doesn't seem needed anyhow else. If this becomes an issue we can look at the use case
