### ISSUE TITLE
Add tenant info to console boot?

### ISSUE THREAD

**Issue by JeremiahChurch** [rails-on-services/apartment#41]
Loving the new custom console!

What would you think about adding a short message on console boot so that folks that aren't familiar with the methods would be introduced to them?

I'm using the below as a quick way to show new devs to an apartment project the console commands without them needing to dig around or ask about them. And thought it might be something that could be incorporated in the gem.

```ruby
# .pryrc
class WelcomeClass
  def self.tenant_info
    ActiveRecord::Base.logger.level = 1
    puts "Available Tenants: #{tenant_list}\n"
    print "Use `st 'tenant'` to switch tenants & `tenant_list` to see list\n"
    ActiveRecord::Base.logger.level = 1
  end
end

# run the code at `bin/rails console`
Pry.config.exec_string = WelcomeClass.tenant_info
```

```
Loading development environment (Rails 6.0.2.2)
Available Tenants: ["public", "ffb", "other"]
Use `st 'tenant'` to switch tenants & `tenant_list` to see list
[1] [development][public] pry(main)>
```

If you're open to the idea I'd be happy to put together a PR.

Thanks for your great work in picking up the maintenance on this gem!

**Comment by rpbaltazar** [comment]
Hi @JeremiahChurch thank you for the feedback. I was very much sure that a lot of people would still be wanting this to move forward.

Sorry for the delays on the answers but i was on leave.

Please do open the PR. I think its quite useful
