### ISSUE TITLE
Error Dropping Tenant

### ISSUE THREAD

**Issue by bmahnke** [rails-on-services/apartment#46]
## Steps to reproduce

0. Postgres Extension Migration:
```
    execute 'CREATE EXTENSION pgcrypto WITH SCHEMA pg_catalog;'
    enable_extension "uuid-ossp"
```
1. Account Model(.rb): 
```
Account(id: uuid, name: string, account_number: string, subdomain: string, created_at: datetime, updated_at: datetime)
```
```
class Account < ApplicationRecord
  after_create :create_tenant
  private
    def create_tenant
      Apartment::Tenant.create(subdomain)
    end
end
```

2. Create database using `ENV` configuration (not `database.yml` (ex: `.env.development`)
```
DATABASE_URL=postgres://##:password@localhost:5432/###
```
3. Create `db/demo.rb` file with content:
```
schemas = Account.all.pluck(:subdomain)
schemas.each do |schema|
  Apartment::Tenant.drop(schema)
end
Account.delete_all
load "db/seeds.rb"
```
4. < Create models to go below account (ex: Users) >
5. Create database: `rails db:drop db:create db:migrate`
6. Seed Data: `rails r db/demo.rb`
7. Reset Database: `rails db:drop db:create db:migrate`

## Expected behavior
I expect the error segment to not appear -- not sure if it's necessarily a bad thing as things _appear_ to be correct in the end and I can seed the database after this with the same `Account` information and the schemas are created.

Appears to be an issue handling `UUID`'s on the tenants? 

## Actual behavior
Error (after step 7):

```
Dropping ["be6c9a5c-66e7-4bc7-8db1-e98b34d7b40b", "First", "73a67d3cf158e61a0b1a", "first", Wed, 06 May 2020 18:20:55 UTC +00:00, Wed, 06 May 2020 18:20:55 UTC +00:00] tenant
Error while dropping tenant ["be6c9a5c-66e7-4bc7-8db1-e98b34d7b40b", "First", "73a67d3cf158e61a0b1a", "first", Wed, 06 May 2020 18:20:55 UTC +00:00, Wed, 06 May 2020 18:20:55 UTC +00:00]: PG::SyntaxError: ERROR:  syntax error at or near "be6c9a5c"
LINE 1: DROP SCHEMA "["be6c9a5c-66e7-4bc7-8db1-e98b34d7b40b", "First...
                       ^
Dropping ["073f33e6-8a21-4e71-9f3c-479ce71f224d", "Second", "019772af66a637c83ba1", "sec", Wed, 06 May 2020 18:20:59 UTC +00:00, Wed, 06 May 2020 18:20:59 UTC +00:00] tenant
Error while dropping tenant ["073f33e6-8a21-4e71-9f3c-479ce71f224d", "Second", "019772af66a637c83ba1", "sec", Wed, 06 May 2020 18:20:59 UTC +00:00, Wed, 06 May 2020 18:20:59 UTC +00:00]: PG::SyntaxError: ERROR:  syntax error at or near "073"
LINE 1: DROP SCHEMA "["073f33e6-8a21-4e71-9f3c-479ce71f224d", "Second...

                       ^
Dropped database 'dev'
Created database 'dev'
... 
<rebuilds database>
```

## System configuration

* Database: (Tell us what database and its version you use.)
`pg-0.21.0`

* Apartment version:
`ros-apartment-2.5.0`

* Apartment config (in `config/initializers/apartment.rb` or so):
```
require 'apartment/elevators/subdomain'
Apartment.configure do |config|
  config.excluded_models = %w{ Account }
  config.tenant_names = lambda { Account.pluck(&:subdomain) }
  config.use_schemas = true 
  config.persistent_schemas = ['shared_extensions']
  config.pg_excluded_names = ["uuid_generate_v4"]
end

Rails.application.config.middleware.use Apartment::Elevators::Subdomain
Apartment::Elevators::Subdomain.excluded_subdomains = ['www', 'admin']
```

* Rails (or ActiveRecord) version:
`6.0.1`

* Ruby version:
`2.6.3`

**Comment by rpbaltazar** [comment]
Thank you for the ticket. Will take a look at it tomorrow to try to reproduce and understand what is causing it.

**Comment by bmahnke** [comment]
Seems to be this line in my `apartment.rb` file. The `&` is the culprit (in my local testing). This issue can probably be closed. 

```
config.tenant_names = lambda { Account.pluck(&:subdomain) }
```

**Comment by rpbaltazar** [comment]
Thank you for the feedback. Your conclusion appears to be correct. Closing this for now
