### ISSUE TITLE
rake db:setup tries to seed non existing tenant

### ISSUE THREAD

**Issue by betelgeuse** [rails-on-services/apartment#52]
## Steps to reproduce

 1. Setup config.tenant_names to a static array
 1. bundle exec rake db:setup

## Expected behavior

  1. create the tenants
  2. seed

## Actual behavior

  1. Seeding gives a warning and does nothing

```
Seeding testtenant1 tenant
One of the following schema(s) is invalid: "testtenant1" "public", "shared_extensions"
```

## System configuration

* Database: (Tell us what database and its version you use.)

PostgresSQL

* Apartment version:

2.6.0

* Apartment config (in `config/initializers/apartment.rb` or so):

  * `use_schemas`: true
  * `persistent_schemas`: %w[shared_extensions]

* Rails (or ActiveRecord) version:

6.0.2.1

* Ruby version:

2.7.0

**Comment by rpbaltazar** [comment]
Thank you for reporting the issue. I'll try to take a look at it still during this week

**Comment by rpbaltazar** [comment]
Resolved with: https://github.com/rails-on-services/apartment/commit/e94a442f81d2d1ca85976230d391455b1d0d97e8
