### ISSUE TITLE
db:rollback uses second latest migration for tenants

### ISSUE THREAD

**Issue by betelgeuse** [rails-on-services/apartment#56]
## Steps to reproduce

rails db:rollback

## Expected behavior

Rolling back latest migration

## Actual behavior

Tenants try to roll back with n - 1.

```
== 20200528194507 Latest: reverting =============================
== 20200528194507 Latest: reverted (0.0526s) ====================

Rolling back testtenant1 tenant
== 20200526235656  SecondLatest: reverting ======================
-- failing_statement
rails aborted!
```

## System configuration

* Database: (Tell us what database and its version you use.) PostgreSQL 10.0

* Apartment version: 2.6.0

* Apartment config (in `config/initializers/apartment.rb` or so):

  *  `tenant_names`: `-> { 'a', 'b', 'dev' }`
  * `use_schemas`: `true`
  * `default_schema`: `dev`
  * `persistent_schemas`: `%w[shared_extensions]`

* Rails (or ActiveRecord) version: 6.0.3

* Ruby version: 2.7.0

**Comment by rpbaltazar** [comment]
Thank you for reporting. I'm able to reproduce it on main development branch. I'll take a look at why is it happening and try to fix it!

**Comment by rpbaltazar** [comment]
Ok, I can see why.
when we enhance the rollback task, we have already ran it for the default schema. but your default schema is also on the list of tenant names, so it rollsback the n-1 for `dev`.
it should be an easy fix.
