### ISSUE TITLE
HISTORY.md has not been updated for latest releases

### ISSUE THREAD

**Issue by betelgeuse** [rails-on-services/apartment#62]
## Steps to reproduce

https://github.com/rails-on-services/apartment/blob/v2.6.1/HISTORY.md

## Expected behavior

Entries for all releases

## Actual behavior

Last entry is for 2.3.0.

If the file is not updated, it should be removed or a header added that it isn't maintained.

**Comment by rpbaltazar** [comment]
@betelgeuse thank you for the feedback. I've been updating the changes on the release notes.
Will make sure those two are in sync.
