### ISSUE TITLE
Undefined method devise with 2.6.1

### ISSUE THREAD

**Issue by exadeci** [rails-on-services/apartment#65]
## Steps to reproduce
- Setup a project with devise and ros-appartment 2.6.1
- Add devise to a user model
- Add the model to the `excluded_models`

## Expected behaviour
No error
## Actual behaviour
```
/Users/gaetan/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `devise' for #<Class:0x00007ffe6480f240> (NoMethodError)
```
## System configuration

* Database: (Tell us what database and its version you use.) Postgres 12

* Apartment version: 2.6.1

* Apartment config (in `config/initializers/apartment.rb` or so):

  * `use_schemas`: `true`

* Rails (or ActiveRecord) version: Rails 6.0.3.1

* Ruby version: ruby 2.6.5p114

Downgrading to 2.6.0 fixes the issue.

**Comment by rpbaltazar** [comment]
I'll try to reproduce the problem on my side. I'm running a project with that setup and i don't see any issues yet. will start with a clean project and see if i can reproduce it

**Comment by rpbaltazar** [comment]
I just tried to spin up a brand new rails project and it seems to work for me. can you open a repository where you can replicate the case? is it possible that you don't have your config/initializers/devise.rb file in the project? I'm able to reproduce it only if i remove the devise initializer.

**Comment by andreslemik** [comment]
@exadeci try to rename `config/initializers/devise.rb` to `config/initializers/00_devise.rb`. It's because during apartment initialization loading User model that's depend from devise, which not loaded yet.

**Comment by rpbaltazar** [comment]
I assume this is caused due to initializer loading the files in the wrong order and not related to apartment anyhow.

**Comment by exadeci** [comment]
@rpbaltazar Yeah it was a load order issue. 

Moving my `CustomElevator.excluded_subdomains =` before `Apartment.configure` fixed it.

**Comment by rpbaltazar** [comment]
If you think it should be added to the documentation, please feel free to submit a PR to update the readme accordingly.
