### ISSUE TITLE
Use a transaction for Apartment::Tenant.create

### ISSUE THREAD

**Issue by betelgeuse** [rails-on-services/apartment#66]
## Steps to reproduce

1. Have tenant creating fail in the middle (by missing functions for example)

## Expected behavior

1. Nothing gets created in the schema

## Actual behavior

1. You get leftover objects

As with PostgreSQL DDL is transaction safe, the schema creation should be wrapped with a transaction.

## System configuration

* Database:  PostgreSQL 10

* Apartment version: 2.6.1

* Apartment config (in `config/initializers/apartment.rb` or so):

  * `use_schemas`: true
  * `persistent_schemas`: %w[shared_extensions]

* Rails (or ActiveRecord) version: 6.0.2.1

* Ruby version: 2.7.0

**Comment by rpbaltazar** [comment]
Do you have an example of a broken scenario that i can use to draft my tests around?
