### ISSUE TITLE
Deprecate History.md

### ISSUE THREAD

**Issue by rpbaltazar** [rails-on-services/apartment#80]
Versions change log is already maintained in the releases. Having an History.md is added work for something that can be achieved by looking at the github releases

**Comment by rpbaltazar** [comment]
After doing some more reading, this seems to be a better solution. Though github releases are a nice to have, having a changelog/history makes more sense for historic reasons.

I shall make some experiments with this
https://github.com/marketplace/actions/automatic-changelog-generator

**Comment by rpbaltazar** [comment]
We're now using github actions to generate the changelog.md.
Once confirmed that the flow is working for us, we'll be removing the history.md file

**Comment by BobbyMcWho** [comment]
It seems like the auto-changelog is broken? missing at least 3 minor releases
