### ISSUE TITLE
Error creating tenant with uuid column

### ISSUE THREAD

**Issue by edbond** [rails-on-services/apartment#85]
## Steps to reproduce

Run
`Apartment::Tenant.create("nfl")`
in console

```
[nfl] SQL (0.3ms) CREATE EXTENSION IF NOT EXISTS "pgcrypto"  []
...
[nfl]  (6.3ms) CREATE TABLE "squirrels" ("id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY, ...

Traceback (most recent call last):
        1: from (irb):2
ActiveRecord::StatementInvalid (PG::UndefinedFunction: ERROR:  function gen_random_uuid() does not exist)
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

## Expected behavior

No errors

## Actual behavior

ActiveRecord::StatementInvalid (PG::UndefinedFunction: ERROR:  function gen_random_uuid() does not exist)
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

## System configuration

* Database: (Tell us what database and its version you use.)

Postgresql server 11.6

* Apartment version:

    ros-apartment (2.7.1)

* Apartment config (in `config/initializers/apartment.rb` or so):

  config.pg_excluded_names = %w[uuid_generate_v4 gen_random_uuid]
  config.tenant_names = -> { DomainSettings.pluck(:name) }

  * `use_schemas`: (`true` or `false`)
  default = true

* Rails (or ActiveRecord) version:

Rails 6.0.2.1

* Ruby version:

ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-darwin18]

**Comment by rpbaltazar** [comment]
Thank you for reporting. I have not yet used the uuid solution, so i have not seen the problem yet. will try to recreate and address the issue over the weekend as well. will keep the ticket updated

**Comment by edbond** [comment]
Thank you Rui. I have found issue in parent repository
https://github.com/influitive/apartment/issues/86

The fix for me was to move pgcrypto extension to pg_catalog:
```sql
ALTER EXTENSION pgcrypto SET SCHEMA pg_catalog;
```

Still don't understand why the function not found after creating pgcrypto extension.
