### ISSUE TITLE
error running db:seed task

### ISSUE THREAD

**Issue by pedrorgomes** [rails-on-services/apartment#86]
## Steps to reproduce

rails db:drop db:create db:migrate db:seed

## Expected behavior

(truncated)
        [WARNING] - The list of tenants to migrate appears to be empty. This could mean a few things:

          1. You may not have created any, in which case you can ignore this message
          2. You've run `apartment:migrate` directly without loading the Rails environment
            * `apartment:migrate` is now deprecated. Tenants will automatically be migrated with `db:migrate`

        Note that your tenants currently haven't been migrated. You'll need to run `db:migrate` to rectify this.
Seeding myapp_development_mygroup tenant

## Actual behavior

(truncated)
        [WARNING] - The list of tenants to migrate appears to be empty. This could mean a few things:

          1. You may not have created any, in which case you can ignore this message
          2. You've run `apartment:migrate` directly without loading the Rails environment
            * `apartment:migrate` is now deprecated. Tenants will automatically be migrated with `db:migrate`

        Note that your tenants currently haven't been migrated. You'll need to run `db:migrate` to rectify this.
Creating myapp_development_mygroup tenant
Error while creating tenant myapp_development_mygroup: Mysql2::Error: Can't create database 'myapp_development_mygroup'; database exists
Seeding myapp_development_mygroup tenant

(Seems like the application tries to create a database before running the seed command.)
## System configuration

* **Database:** Mysql 8.0.20

* **Apartment version:** 2.7.1

* **Apartment config (in `config/initializers/apartment.rb` or so):**  #config.use_schemas = true (line is commented)

* **Rails (or ActiveRecord) version:** 6.0.3.2

* **Ruby version:** 2.7.1

I'm getting an error while running db:seed. It looks like the application tries to create a database before running the seed command. Everything runs ok at version 2.7.0

Due to this commit:
https://github.com/rails-on-services/apartment/pull/84/commits/b6af077ceb4b16b3a5e27c0126f8d645107b5a24
[apartment.zip](https://github.com/rails-on-services/apartment/files/4920274/apartment.zip)

**Comment by rpbaltazar** [comment]
Thank you for reporting, Will be addressing this issue over the weekend

**Comment by rpbaltazar** [comment]
can you please paste your `apartment.rb` file in here in the ticket? 
I have tried to replicate the scenario that you're describing and can't seem to be able to reproduce it:
https://github.com/rails-on-services/rails-6-demo/tree/rails-app-using-mysql

**Comment by pedrorgomes** [comment]
@rpbaltazar I have attached the apartment.rb file

**Comment by rpbaltazar** [comment]
@pedrorgomes I'm having some issue reproducing your error. It's either a configuration problem on your app or on my demo. That being said, in order for me to help you further, you can create a simple repo with the problem happening that i can checkout and debug or we can try to jump on a sharing screen session where you show me the project setup and we do a bit of testing against the apartment itself.

**Comment by rpbaltazar** [comment]
I commented on the PR, but i meant to write it here.
Without being able to replicate the actual reported bug, this (#87) is the best i can do at the moment. I'll close the issue as well. If this is still a problem, then we'll need to investigate further how to find out the source of the problem. Feel free to test against the development branch and if the problem still persists, let me know and we'll try to sort it out.
